# -*- coding: utf-8 -*-
import logging
from uuid import uuid4

import pytz
from icalendar import Calendar, Event
from datetime import datetime, timedelta
from pathlib import Path
import os


class iCal():
	def __init__(self):
		self._cal = Calendar()
		self.cal['prodid'] = '-//Pregnancy calendar product//Nadav Angel//EN'
		self.cal['version'] = '2.0'
		self.cal['summary'] = 'A Pregnancy calendar auto-generated by Python'
		self.now = datetime.now()
	
	@property
	def cal(self) -> Calendar:
		return self._cal
	
	def addEvent(self, date: datetime, name: str, description: str = ""):
		event = Event()
		event['uid'] = str(uuid4())
		event['name'] = name
		event['SUMMARY'] = name
		if description != "":
			event['description'] = description
		
		event['DTSTART;VALUE=DATE'] = date.strftime('%Y%m%d')#19970714T170000Z
		event['DTEND;VALUE=DATE'] = (date + timedelta(1)).strftime('%Y%m%d')
		event['DTSTAMP'] = self.now.strftime('%Y%m%dT%H%M%S%z') #19970714T170000Z
		event['CREATED'] = self.now.strftime('%Y%m%dT%H%M%S%z')
		event['LAST-MODIFIED'] = self.now.strftime('%Y%m%dT%H%M%S%z')
		event['X-MICROSOFT-CDO-BUSYSTATUS'] = 'FREE'

		self.cal.add_component(event)
		
	def writeFile(self, directory: Path, fileName: str):
		with open(os.path.join(directory, fileName + '.ics'), 'wb') as f:
			f.write(self.cal.to_ical())


class PregnancyICal():
	_cal: iCal
	_lmp: datetime | None
	_allDays: bool
	_addTrimester: bool
	
	def __init__(self, lastMonthlyPeriod: datetime | None = None):
		self._cal = iCal()
		self._lmp = lastMonthlyPeriod
		self._allDays = True
		self._addTrimester = True
	
	@property
	def lmp(self) -> datetime:
		return self._lmp
	
	@lmp.setter
	def lmp(self, value: datetime) -> None:
		self._lmp = value
	
	@property
	def allDays(self) -> bool:
		return self._allDays
	
	@allDays.setter
	def allDays(self, value: bool) -> None:
		self._allDays = value
	
	@property
	def addTrimester(self) -> bool:
		return self._addTrimester
	
	@addTrimester.setter
	def addTrimester(self, value: bool) -> None:
		self._addTrimester = value
	
	def write(self, directory: Path):
		self.addEvents()
		self._cal.writeFile(directory=directory, fileName='PregnancyCalendar')
	
	def addEvents(self):
		if self.lmp is None:
			raise ValueError(f'Missing last monthly period')
		
		if self.allDays:
			self._addAllDaysEvents()
		else:
			self._addFirstDayOfWeekEvents()
		
		if self.addTrimester:
			self._addTrimseterEvents()
			
		self._cal.addEvent(self.lmp + timedelta(281), 'Expected date!!')
			
	def _addAllDaysEvents(self):
		for day in range(14, 280):
			this_day = self.lmp + timedelta(day)
			week_num = int(day / 7)
			day_of_week = day % 7
			self._cal.addEvent(date=this_day, name = f'week {week_num} day {day_of_week}')
	
	def _addFirstDayOfWeekEvents(self):
		pass
	
	def _addTrimseterEvents(self):
		pass
	